services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.anzensolutions.com"
      SIGNUPS_ALLOWED: "false"
      # WEBSOCKET_ENABLED: "true"
      # ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      # SMTP_HOST: smtp.domain.tld 
      # SMTP_FROM: vaultwarden@domain.tld 
      # SMTP_PORT: 587 
      # SMTP_SECURITY: starttls 
      # SMTP_USERNAME: myusername 
      # SMTP_PASSWORD: MyPassw0rd
    volumes:
      - /home/steven/vaultwarden/:/data/
    # ports:
    #   - 8960:80
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Entry Point for https
      - "traefik.http.routers.vaultwarden.rule=Host(`vw.anzensolutions.com`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=cloudflare"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      # Required headers for SharedArrayBuffer (LibreOffice WASM)
      # - "traefik.http.routers.vaultwarden.middlewares=vaultwarden-headers"
      # - "traefik.http.middlewares.vaultwarden-headers.headers.customresponseheaders.Cross-Origin-Opener-Policy=same-origin"
      # - "traefik.http.middlewares.vaultwarden-headers.headers.customresponseheaders.Cross-Origin-Embedder-Policy=require-corp"
networks:
  traefik:
    external: true